github.com:
    git_protocol: ssh
    users:
        cut-the-freakin-steak:
            oauth_token: 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
    user: cut-the-freakin-steak
    oauth_token: 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
