github.com:
    git_protocol: ssh
    users:
        cut-the-freakin-steak:
            oauth_token: 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
    user: cut-the-freakin-steak
    oauth_token: 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
