# ==============================================================================
# USER CONFIGURATION: autostart.conf
# ==============================================================================
# Add your custom settings for autostart here.
# These will override or add to the defaults found in ~/.config/hypr/source/autostart.conf
# ==============================================================================


# load plugins on startup
exec-once = hyprpm reload -n

# make the dumbass clipboard persist through apps dying good lord.
exec-once = wl-clip-persist --clipboard regular

# set cursor
# on startup
exec-once = hyprctl setcursor WiiPointer 43

# set gtk-theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme Catppuccin-Mocha

# make dolphin great again
exec-once = XDG_MENU_PREFIX=arch- kbuildsycoca6

# NOTE: startup apps
exec-once = helium-browser
exec-once = steam
exec-once = blueman-applet
