# ==============================================================================
# USER CONFIGURATION: window_rules.conf
# ==============================================================================
# Add your custom settings for window_rules here.
# These will override or add to the defaults found in ~/.config/hypr/source/window_rules.conf
# ==============================================================================

# steam main window
windowrule {
    name = steam-main-window
    match:class = ^(steam)$
    match:title = ^(Steam)$
    size = 1300 850
    center = on
}

# steam friends window
windowrule {
    name = steam-friends
    match:class = ^(steam)$
    match:title = ^(Friends List)$
    size = 500 700
	center = on
}

# blueman
windowrule {
    name = float-blueman
    match:class = ^(blueman-manager)$
    float = on
    size = 650 500
    center = on
}

# pavucontrol
windowrule {
    name = float-pavucontrol
    match:class = ^(pavucontrol|org.pulseaudio.pavucontrol)$
    float = on
    size = 1000 650
    center = on
}


# common dialogs (like file pickers)
windowrule {
    name = float-dialogs-title

# regex logic:
# matches specific phrases OR any title containing "dialog"
    match:title = ^(Open|Open File|Open Kvantum Theme Folder|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload|Authentication Required|Add Folder to Workspace|Choose Files|Confirm to replace files|File Operation Progress)(.*)$|^(.*dialog.*)$

    float = on
    center = on
    size = 1000 800
}

# satty
windowrule {
	name = float-satty
	match:class = ^(com.gabm.satty)$
	float = on
	center = on
	size = 1280 800
}
