[color]
background = 'default'
foreground = '#ebf0ff'

; gradient = 0
gradient = 1
gradient_color_1 = '#a4c3ff'
gradient_color_2 = '#ebf0ff'
gradient_color_3 = '#000000'

horizontal_gradient = 0
; horizontal_gradient = 1
horizontal_gradient_color_1 = '#a4c3ff'
horizontal_gradient_color_2 = '#ebf0ff'
horizontal_gradient_color_3 = '#000000'
horizontal_gradient_color_4 = '#ebf0ff'
horizontal_gradient_color_5 = '#a4c3ff'


