#  ┏┓┏┓┏┓┏┳┓┳┏┓┓┏  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓
#  ┗┓┃┃┃┃ ┃ ┃┣ ┗┫━━┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃
#  ┗┛┣┛┗┛ ┻ ┻┻ ┗┛  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗
#                                  


[Comfy]
text               = ffffff
subtext            = ffffff
main               = 17111b
main-elevated      = 554d59
main-transition    = 000000
highlight          = 231d27
highlight-elevated = 4c444f
sidebar            = 17111b
player             = 000000
card               = 000000
shadow             = 000000
selected-row       = ffffff
button             = ebf0ff
button-active      = d6e3ff
button-disabled    = aac7ff
tab-active         = 17111b
notification       = faebff
notification-error = ffece9
misc               = 000000
play-button        = ebf0ff
play-button-active = d6e3ff
progress-fg        = ebf0ff
progress-bg        = 17111b
heart              = ffece9
pagelink-active    = 000000
radio-btn-active   = 000000